#!/usr/bin/env python3

dream_cars = {"car_1": "bugatti", "car_2": "ferarri"}
boats = ["Pinta", "Nina", "Santa Maria"]

# The bugatti was on the Santa Maria and the ferarri was on the Pinta


print("The " + dream_cars['car_1'] +  " was on the " + boats[2] + " and the " + dream_cars['car_2'] + " was on the " +  boats[0])
print(f"The  {dream_cars['car_1']}  was on the  {boats[2]}  and the  {dream_cars['car_2']}  was on the  {boats[0]}")

